apiVersion: v2
kind: Deployment
metadata:
  name: hello-world4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world4
  template:
    metadata:
      labels:
        app: hello-world4
    spec:
      containers:
      - name: hello-world
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080

